#ifndef __CONSOLE_H__
#define __CONSOLE_H__

#include "Types.h"

// 매크로

// 비디오 속성 값 설정
#define CONSOLE_BACKGROUND_BLACK 0x00
#define CONSOLE_BACKGROUND_BLUE 0x10
#define CONSOLE_BACKGROUND_GREEN 0x20
#define CONSOLE_BACKGROUND_CYAN 0x30
#define CONSOLE_BACKGROUND_RED 0x40
#define CONSOLE_BACKGROUND_MAGENTA 0x50
#define CONSOLE_BACKGROUND_BROWN 0x60
#define CONSOLE_BACKGROUND_WHITE 0x70
#define CONSOLE_BACKGROUND_BLINK 0x80
#define CONSOLE_FOREGROUND_DARKBLACK 0x00
#define CONSOLE_FOREGROUND_DARKBLUE 0x01
#define CONSOLE_FOREGROUND_DARKGREEN 0x02
#define CONSOLE_FOREGROUND_DARKCYAN 0x03
#define CONSOLE_FOREGROUND_DARKRED 0x04
#define CONSOLE_FOREGROUND_DARKMAGENTA 0x05
#define CONSOLE_FOREGROUND_DARKBROWN 0x06
#define CONSOLE_FOREGROUND_DARKWHITE 0x07
#define CONSOLE_FOREGROUND_BRIGHTBLACK 0x08
#define CONSOLE_FOREGROUND_BRIGHTBLUE 0x09
#define CONSOLE_FOREGROUND_BRIGHTGREEN 0x0A
#define CONSOLE_FOREGROUND_BRIGHTCYAN 0x0B
#define CONSOLE_FOREGROUND_BRIGHTRED 0x0C
#define CONSOLE_FOREGROUND_BRIGHTMAGENTA 0x0D
#define CONSOLE_FOREGROUND_BRIGHTYELLOW 0x0E
#define CONSOLE_FOREGROUND_BRIGHTWHITE 0x0F

// 기본 문자 색
#define CONSOLE_DEFAULTTEXTCOLOR (CONSOLE_BACKGROUND_BLACK | CONSOLE_FOREGROUND_BRIGHTGREEN)

// 사용자 설정 색
// 관련 매크로
#define DEFAULTMESSAGE 0
#define ERRORMESSAGE 1
#define PROMPTMESSAGE 2
#define INPUTMESSAGE 3

#define LKY_DEFAULTTEXTCOLOR (CONSOLE_BACKGROUND_BLACK | CONSOLE_FOREGROUND_BRIGHTGREEN) // 기본
#define LKY_ERRORTEXTCOLOR (CONSOLE_BACKGROUND_BLACK | CONSOLE_FOREGROUND_BRIGHTRED) // 에러
#define LKY_PROMPTTEXTCOLOR (CONSOLE_BACKGROUND_BLACK | CONSOLE_FOREGROUND_BRIGHTYELLOW) // 프롬프트
#define LKY_INPUTTEXTCOLOR (CONSOLE_BACKGROUND_BLACK | CONSOLE_FOREGROUND_DARKWHITE) // 입력

// 콘솔 설정 값, 비디오 메모리 주소 설정
#define CONSOLE_WIDTH 80
#define CONSOLE_HEIGHT 25
#define CONSOLE_VIDEOMEMORYADDRESS 0xB8000

// 비디오 컨트롤러의 I/O 포트 어드레스, 또 레지스터(상위, 하위)
#define VGA_PORT_INDEX 0x3D4
#define VGA_PORT_DATA 0x3D5
#define VGA_INDEX_UPPERCURSOR 0x0E
#define VGA_INDEX_LOWERCURSOR 0x0F

// 구조체
#pragma pack(push, 1)

// 콘솔에 대한 정보 저장 자료구조
typedef struct kConsoleManagerStruct{
	// 현 커서 위치(오프셋)
	int iCurrentPrintOffset;
}CONSOLEMANAGER;

#pragma pack(pop)

// 함수
void kInitializeConsole(int iX, int iY);
void kSetCursor(int iX, int iY);
void kGetCursor(int* piX, int* piY);
void kPrintf(const char* pcFormatString, ...);
void kLKYPrintf(int iType, const char* pcFormatString, ...);
int kConsolePrintString(int iType, const char* pcBuffer);
void kClearScreen(void);
BYTE kGetCh(void);
void kPrintStringXY(int iX, int iY, const char* pcString);

#endif /*__CONSOLE_H__*/

